name: "testing simple yaml workflow"
on:
    workflow_dispatch
permissions:
    id-token: write
    contents: read


jobs:
   testingjob:
    runs-on: ubuntu-latest
    environment: dev
    
    defaults:
      run:
       shell: bash
       working-directory: ./
    steps:
     - name: Checkout
       uses: actions/checkout@v4
     - name: Azure CLI script
       uses: azure/cli@v1
       with:
        client_id: ${{ secrets.ARM_CLIENT_ID}}
        subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        tenant_id: ${{ secrets.ARM_TENANT_ID}}
        ARM_USE_OIDC: true
     - name: Setup terraform
       uses: hashicorp/setup-terraform@v3
     - name: Terraform fmt
       id: fmt
       run: terraform fmt -check
       continue-on-error: true

     - name: Terraform Init
       id: init
       run: terraform init -input=false
     - name: Terraform Plan
       id: plan
       run: terraform plan -no-color -input=false
       continue-on-error: true
   apply:
    needs: testingjob
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
       shell: bash
       working-directory: ./
    steps:
     - name: Checkout
       uses: actions/checkout@v4
     - name: Azure CLI script
       uses: azure/cli@v1
       with:
        client_id: ${{ secrets.ARM_CLIENT_ID}}
        subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        tenant_id: ${{ secrets.ARM_TENANT_ID}}
        ARM_USE_OIDC: true
     - name: Setup terraform
       uses: hashicorp/setup-terraform@v3   
     - name: Terraform Apply
       id: apply
       run: terraform apply --auto-approve
     
        
    
